<?php
namespace Grav\Plugin\MigrateGrav;

/**
 * Detects and remediates direct web access to the sensitive `user/` folders
 * (accounts, config, data) and the same three inside each `user/env/<name>/`.
 *
 * Older Grav installs ship a site root `.htaccess` that only blocks a fixed
 * list of file extensions under `user/`. Files stored under `user/data` with
 * an unlisted extension (certificates, keys, tokens, sqlite databases, logs)
 * could therefore be downloaded directly over HTTP. Grav 1.7.53 and 2.0 block
 * these folders, apart from avatar images and public media uploads; this helper
 * brings an older install up to the same rules, and warns when the webserver
 * is not Apache and the fix has to be applied to the server config by hand.
 */
class HtaccessSecurity
{
    /**
     * Folders under user/ that are denied outright, each getting a backup .htaccess.
     * user/env is not one: a multisite keeps its themes, plugins and media there, so
     * only the config, accounts and data inside each env folder are blocked, by the
     * root rules. Grav ships no user/env/.htaccess, so this fix writes none either
     * (getgrav/grav#4335).
     */
    public const SENSITIVE = ['accounts', 'config', 'data'];

    /** Signature of the blanket folder block earlier versions of this plugin added. */
    private const RULE_SIGNATURE = '^(user)/(accounts|config|data|env)/';

    /** Signature of the config rule Grav 2.2.4 ships, which covers env folders without blocking their assets. */
    private const ENV_RULE_SIGNATURE = '^(user)/(env/[^/]+/)?config/';

    /**
     * The folder block Grav 2.2.4 ships, with its avatar and media exceptions.
     * Keep in step with webserver-configs/htaccess.txt.
     */
    private const ROOT_RULES = <<<'HTACCESS'
# Block all direct access to these sensitive user folders, whatever the file type
RewriteRule ^(user)/(env/[^/]+/)?config/(.*) error [F,NC]
# Block user/accounts too, but allow avatar images to be served directly,
# whether stored at user/accounts/avatars/<file> (flatfile accounts) or
# user/accounts/<username>/<file> (Flex folder storage). Account data
# (.yaml password hashes) stays blocked; SVG is excluded as a stored-XSS vector.
RewriteCond %{REQUEST_URI} !/user/(env/[^/]+/)?accounts/[^/]+/[^/]+\.(jpe?g|png|gif|webp|avif|bmp|ico)$ [NC]
RewriteRule ^(user)/(env/[^/]+/)?accounts/(.*) error [F,NC]
# Block user/data too, but allow public asset uploads (e.g. Flex Object images)
# to be served directly. SVG stays blocked as a stored-XSS vector; .css/.js are
# served per project policy despite the same risk on this user-writable folder.
RewriteCond %{REQUEST_URI} !\.(jpe?g|png|gif|webp|avif|bmp|ico|mp4|webm|ogg|ogv|mov|mp3|wav|m4a|flac|pdf|woff2|woff|ttf|otf|eot|css|js)$ [NC]
RewriteRule ^(user)/(env/[^/]+/)?data/(.*) error [F,NC]
HTACCESS;

    // BEGIN generated by scripts/build-htaccess-reference.php from grav develop (1ca03ace8). Do not edit by hand.
    /** The Grav 2 .htaccess file for each sensitive user/ folder. */
    private const CURRENT = array (
  'accounts' => '# Deny direct web access to this folder, except avatar images (account://avatars)
# that Grav serves over HTTP. Account data (.yaml password hashes), databases,
# keys and tokens stay blocked; SVG is excluded as a stored-XSS vector.
# Defense-in-depth backup for the rules in the site root .htaccess.
#
# mod_alias, not `Require` or mod_rewrite. `Require` is AuthConfig-class and
# returns 500 for this whole folder on a host that grants only `AllowOverride
# FileInfo` (getgrav/grav#4309, #4311). mod_alias is FileInfo-class, leaves the
# root\'s rewrite rules in force here, and merges into subfolders, so a subfolder
# with its own RewriteEngine cannot switch it off.
#
# Matches the whole URL path, so the exception is written exactly as the root\'s.
# Keep the two in sync.
<IfModule mod_alias.c>
    RedirectMatch 403 (?i)^(?!.*/user/accounts/[^/]+/[^/]+\\.(jpe?g|png|gif|webp|avif|bmp|ico)$)
</IfModule>
',
  'config' => '# Deny all direct web access to this folder and everything beneath it.
# Grav reads these files server-side; they must never be served over HTTP.
# This is a defense-in-depth backup for the rules in the site root .htaccess.
#
# mod_alias, not `Require` or mod_rewrite. `Require` is AuthConfig-class and
# returns 500 for this whole folder on a host that grants only `AllowOverride
# FileInfo` (getgrav/grav#4309, #4311). mod_alias is FileInfo-class, leaves the
# root\'s rewrite rules in force here, and merges into subfolders, so a subfolder
# with its own RewriteEngine cannot switch it off.
<IfModule mod_alias.c>
    RedirectMatch 403 .*
</IfModule>
',
  'data' => '# Deny direct web access to this folder, except the public asset uploads
# (e.g. Flex Object images) that Grav has always served from here.
# Data files (.yaml/.json/.md), databases, keys and tokens stay blocked.
# SVG stays blocked as a stored-XSS vector; .css/.js are served per project
# policy despite the same risk on this user-writable folder.
# Defense-in-depth backup for the rules in the site root .htaccess.
#
# mod_alias, not `Require` or mod_rewrite. `Require` is AuthConfig-class and
# returns 500 for this whole folder on a host that grants only `AllowOverride
# FileInfo` (getgrav/grav#4309, #4311). mod_alias is FileInfo-class, leaves the
# root\'s rewrite rules in force here, and merges into subfolders, so a subfolder
# with its own RewriteEngine cannot switch it off.
#
# Keep the extension list in sync with the root\'s user/data rule.
<IfModule mod_alias.c>
    RedirectMatch 403 (?i)^(?!.*\\.(jpe?g|png|gif|webp|avif|bmp|ico|mp4|webm|ogg|ogv|mov|mp3|wav|m4a|flac|pdf|woff2|woff|ttf|otf|eot|css|js)$)
</IfModule>
',
);
    // END generated

    private string $root;

    public function __construct(string $root)
    {
        $this->root = rtrim($root, '/');
    }

    public function serverSoftware(): string
    {
        return strtolower((string) ($_SERVER['SERVER_SOFTWARE'] ?? ''));
    }

    /**
     * LiteSpeed honours .htaccess too, so it counts as Apache-compatible here.
     */
    public function isApache(): bool
    {
        $s = $this->serverSoftware();
        return $s === '' ? false : (str_contains($s, 'apache') || str_contains($s, 'litespeed'));
    }

    public function rootHtaccessPath(): string
    {
        return $this->root . '/.htaccess';
    }

    /**
     * Either folder block Grav ships (1.7.53 and 2.2.4) or the blanket one this plugin used to add.
     */
    public function hasRootRule(): bool
    {
        $f = $this->rootHtaccessPath();
        if (!is_file($f)) {
            return false;
        }
        $contents = (string) @file_get_contents($f);

        return str_contains($contents, self::RULE_SIGNATURE)
            || str_contains($contents, self::ENV_RULE_SIGNATURE)
            || (str_contains($contents, '^(user)/(config|env)/')
                && str_contains($contents, '^(user)/accounts/')
                && str_contains($contents, '^(user)/data/'));
    }

    /**
     * Folders that exist but do not yet carry a backup deny-all .htaccess.
     *
     * @return string[]
     */
    public function unprotectedDirs(): array
    {
        $missing = [];
        foreach (self::SENSITIVE as $folder) {
            $dir = $this->root . '/user/' . $folder;
            if (is_dir($dir) && !is_file($dir . '/.htaccess')) {
                $missing[] = $folder;
            }
        }
        return $missing;
    }

    /**
     * @return array{protected: bool, apache: bool, server: string, root_rule: bool, can_autofix: bool, unprotected: string[]}
     */
    public function status(): array
    {
        $apache       = $this->isApache();
        $rootRule     = $this->hasRootRule();
        $unprotected  = $this->unprotectedDirs();
        $perDirCovers = $unprotected === [];

        // On Apache the install is protected once either the root rule is in
        // place or every sensitive folder has its own deny file. On any other
        // server, .htaccess is ignored entirely, so we cannot self-protect and
        // must defer to a manual server-config change.
        $protected = $apache && ($rootRule || $perDirCovers);

        // We can only safely auto-fix when Apache is serving the site and the
        // root .htaccess (if present) is writable.
        $rootWritable = !is_file($this->rootHtaccessPath()) || is_writable($this->rootHtaccessPath());
        $canAutofix   = $apache && !$protected && $rootWritable;

        return [
            'protected'   => $protected,
            'apache'      => $apache,
            'server'      => $this->serverSoftware(),
            'root_rule'   => $rootRule,
            'can_autofix' => $canAutofix,
            'unprotected' => $unprotected,
        ];
    }

    /**
     * Patch the root .htaccess and drop per-folder deny files.
     *
     * @return array{patched: bool, created: string[], errors: string[]}
     */
    public function applyFix(): array
    {
        $created = [];
        $errors  = [];

        foreach (self::SENSITIVE as $folder) {
            $dir = $this->root . '/user/' . $folder;
            if (!is_dir($dir)) {
                continue;
            }
            $file = $dir . '/.htaccess';
            if (is_file($file)) {
                continue;
            }
            if (!is_writable($dir)) {
                $errors[] = "user/$folder is not writable";
                continue;
            }
            // Grav 2's own copy: mod_alias, not `Require`, which answers 500 for the
            // whole folder on hosts that allow only `AllowOverride FileInfo`, and
            // with the same avatar and media exceptions as the root rules.
            if (@file_put_contents($file, self::CURRENT[$folder]) !== false) {
                $created[] = "user/$folder/.htaccess";
            } else {
                $errors[] = "could not write user/$folder/.htaccess";
            }
        }

        $patched = false;
        $root    = $this->rootHtaccessPath();
        if (is_file($root)) {
            if (!is_writable($root)) {
                $errors[] = '.htaccess is not writable';
            } elseif (!$this->hasRootRule()) {
                $contents = (string) @file_get_contents($root);
                $count = 0;
                // After the stock folder block, whose flags and folder list vary by release.
                $new = preg_replace_callback(
                    '/^RewriteRule \^\(\\\\\.git\|cache\|bin\|logs\|backup\|[^)\r\n]*\)\/\(\.\*\) error \[F(?:,NC)?\][ \t]*(\r?\n)/m',
                    static fn(array $m) => $m[0] . str_replace("\n", $m[1], self::ROOT_RULES) . $m[1],
                    $contents,
                    1,
                    $count
                );
                if ($count > 0 && is_string($new) && $new !== $contents) {
                    if (@file_put_contents($root, $new) !== false) {
                        $patched = true;
                    } else {
                        $errors[] = 'could not write patched .htaccess';
                    }
                } else {
                    $errors[] = 'could not locate the Grav security block in .htaccess to patch';
                }
            }
        }

        return ['patched' => $patched, 'created' => $created, 'errors' => $errors];
    }

    /**
     * The rules an operator must add by hand when the site is not on Apache.
     */
    public function manualSnippet(): string
    {
        $s = $this->serverSoftware();
        if (str_contains($s, 'nginx')) {
            // As Grav's webserver-configs/nginx.conf: the allow rules must come first.
            return "location ~* ^/user/(env/[^/]+/)?config/.*$ { return 403; }\n"
                . "location ~* ^/user/(env/[^/]+/)?accounts/[^/]+/[^/]+\\.(jpe?g|png|gif|webp|avif|bmp|ico)$ { try_files \$uri =404; }\n"
                . "location ~* ^/user/(env/[^/]+/)?accounts/.*$ { return 403; }\n"
                . "location ~* ^/user/(env/[^/]+/)?data/.*\\.(jpe?g|png|gif|webp|avif|bmp|ico|mp4|webm|ogg|ogv|mov|mp3|wav|m4a|flac|pdf)$ { try_files \$uri =404; }\n"
                . "location ~* ^/user/(env/[^/]+/)?data/.*$ { return 403; }";
        }
        if (str_contains($s, 'iis') || str_contains($s, 'microsoft')) {
            return '<rule name="user_sensitive_folders" stopProcessing="true">' . "\n"
                . '    <match url="^user/(env/[^/]+/)?(accounts|config|data)/(.*)" ignoreCase="false" />' . "\n"
                . '    <action type="Redirect" url="error" redirectType="Permanent" />' . "\n"
                . '</rule>';
        }
        if (str_contains($s, 'caddy')) {
            // Caddy's `path` matcher is literal — a bare
            // `rewrite /user/(accounts|...)/.* /403` reads as a literal path
            // and matches nothing, so this has to be a named `path_regexp`
            // matcher answering 403 itself. It also has to sit inside the
            // `route` block ahead of the `try_files` rewrite: outside a route
            // Caddy runs the rewrite first and this never sees the request.
            return "@grav_user_sensitive path_regexp (?i)^/user/(env/[^/]+/)?(accounts|config|data)/\n"
                . "respond @grav_user_sensitive 403";
        }
        if (str_contains($s, 'lighttpd')) {
            return '$HTTP["url"] =~ "^/user/(env/[^/]+/)?(accounts|config|data)/(.*)" { url.access-deny = ("") }';
        }
        return self::ROOT_RULES;
    }
}
